### ISSUE TITLE
DExTool.py fails when exporting annotations

### ISSUE THREAD

**Issue by psk9211** [Vicomtech/DMD-Driver-Monitoring-Dataset#1]
Hello.

I faced an error during the annotation export using DExTool.py
There was two types of errors under different conditions.

First is `moov atom not found` error and it occurs when export annotations by group.

```bash
$python DExTool.py

Welcome :)
What do you whish to do?:  export material for training:[0]  group exported material by classes:[1]  create train and test split:[2] : 0
To change export settings go to accessDMDAnn.py and change control variables.
Enter destination path: ~/
How do you want to read annotations, by: Group:[g]  Sessions:[f]  One VCD:[v] : g
Enter DMD group's path (../dmd/g#): /data/dmd/gA
Enter the session you wish to export in this group:  all:[0]  S1:[1]  S2:[2]  S3[3]  S4[4] : 0
/data/dmd/gA/1
/data/dmd/gA/1/s1
/data/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_rgb_ann_distraction.json
There are 12 actions in this VCD


-- Getting data of rgb channel --


-- Creating image of action: gaze_on_road/looking_road --
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ec4b3cfac0] moov atom not found
length of video:/data/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_rgb_body.mp4 is 0.
Doesn't match to 6762
Traceback (most recent call last):
  File "DExTool.py", line 43, in <module>
    exportClass(annotation,str(dmd_folder),destination_path)
  File "/data/DMD-Driver-Monitoring-Dataset/exploreMaterial-tool/accessDMDAnn.py", line 107, in __init__
    self.exportMaterial(material, streams, channels, annotations, write, intervalChunk, True)
  File "/data/DMD-Driver-Monitoring-Dataset/exploreMaterial-tool/accessDMDAnn.py", line 136, in exportMaterial
    intervals = self.getIntervals(
  File "/data/DMD-Driver-Monitoring-Dataset/exploreMaterial-tool/accessDMDAnn.py", line 150, in getIntervals
    streamVideoPath = str(self.getStreamVideo(channel, stream))
  File "/data/DMD-Driver-Monitoring-Dataset/exploreMaterial-tool/accessDMDAnn.py", line 389, in getStreamVideo
    raise RuntimeWarning(
RuntimeWarning: VCD's and real video frame count don't match.
```

Second is `Invalid NAL unit size` error, when exporting by one VCD.

```bash
-- Getting data of ir channel --


-- Creating image of action: gaze_on_road/looking_road --
ir hands stream loaded: gA_5_s4_2019-03-22T11;28;00+01;00_ir_hands.mp4
Writing...
WARNING: Skipped interval 0, because some of its frames do not exist in stream hands
[h264 @ 0x55f443b911c0] error while decoding MB 10 35, bytestream -21
[h264 @ 0x55f443b97b00] Invalid NAL unit size (0 > 24466).
[h264 @ 0x55f443b97b00] Error splitting the input into NAL units.
[h264 @ 0x55f44422b6c0] Invalid NAL unit size (0 > 118934).
[h264 @ 0x55f44422b6c0] Error splitting the input into NAL units.
[h264 @ 0x55f4441d7680] Invalid NAL unit size (0 > 21411).
[h264 @ 0x55f4441d7680] Error splitting the input into NAL units.
[h264 @ 0x55f443cccc00] Invalid NAL unit size (0 > 23385).
[h264 @ 0x55f443cccc00] Error splitting the input into NAL units.
[h264 @ 0x55f443bae6c0] Invalid NAL unit size (0 > 118608).
[h264 @ 0x55f443bae6c0] Error splitting the input into NAL units.
[h264 @ 0x55f443bcb240] Invalid NAL unit size (0 > 19541).
[h264 @ 0x55f443bcb240] Error splitting the input into NAL units.
[h264 @ 0x55f443be7dc0] Invalid NAL unit size (0 > 23940).
[h264 @ 0x55f443be7dc0] Error splitting the input into NAL units.
...
```

So I checked the indivisual video files using `ffprobe`, and this error showed up:
```bash
$ ffprobe  -print_format json -show_format -show_streams /data/dmd/gA/1/s2/gA_1_s2_2019-03-08T09\;21\;03+01\;00_ir_body.mp4 
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
{
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559f3371b480] moov atom not found
/data/dmd/gA/1/s2/gA_1_s2_2019-03-08T09;21;03+01;00_ir_body.mp4: Invalid data found when processing input

}
```

which should be like this:
```bash
$ ffprobe  -print_format json -show_format -show_streams /data/dmd/gA/1/s2/gA_1_s2_2019-03-08T09\;21\;03+01\;00_rgb_hands.mp4 
ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
{
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/dmd/gA/1/s2/gA_1_s2_2019-03-08T09;21;03+01;00_rgb_hands.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:07:37.63, start: 0.000000, bitrate: 15172 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1280x720, 15171 kb/s, 29.76 fps, 29.76 tbr, 11904 tbn, 59.52 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High 4:4:4 Predictive",
            "codec_type": "video",
            "codec_time_base": "25/1488",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "has_b_frames": 0,
            "sample_aspect_ratio": "0:1",
            "display_aspect_ratio": "0:1",
            "pix_fmt": "yuv444p",
            "level": 31,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "744/25",
            "avg_frame_rate": "744/25",
            "time_base": "1/11904",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 5447604,
            "duration": "457.628024",
            "bit_rate": "15171366",
            "bits_per_raw_sample": "8",
            "nb_frames": "13619",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "VideoHandler"
            }
        }
    ],
    "format": {
        "filename": "/data/dmd/gA/1/s2/gA_1_s2_2019-03-08T09;21;03+01;00_rgb_hands.mp4",
        "nb_streams": 1,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "457.628000",
        "size": "867936596",
        "bit_rate": "15172788",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "encoder": "Lavf56.40.101"
        }
    }
}
```

I didn't test all the videos with ffprobe, but it looks like quite a lot of videos are not wroking properly with ffmpeg.
Dataset was downloaded through the box shared folder.

Here's my system informations:

### System information
- OS: Ubuntu 18.04.1 64-bit
- GCC v7.5.0
- python 3.8.8 (conda env)
- ffmpeg 3.4.8
- ffmpeg-python v.0.2.0
- OpenCV-python v4.5.2.52
- VCD v4.3.1

Any comments or advices would be appreciated.
Thank you.

**Comment by pncanas333** [comment]
Hello @psk9211. Thanks for posting the error.

I see that you had trouble with the video: gA_1_s1_2019-03-08T09;31;15+01;00_rgb_body.mp4
I tried to reproduce the error by downloading (from Box) the files from folder: /dmd/gA/1/s1/*, then executing DExTool.py with the options you typed: export material for training, by group, all sessions. And it worked.

```
/home/pncanas/Desktop/annotator/dmd/gA/1
/home/pncanas/Desktop/annotator/dmd/gA/1/s1
/home/pncanas/Desktop/annotator/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_rgb_ann_distraction.json
There are 12 actions in this VCD

-- Getting data of rgb channel --

-- Creating image of action: gaze_on_road/looking_road --
rgb body stream loaded: gA_1_s1_2019-03-08T09;31;15+01;00_rgb_body.mp4
Writing...
Directory looking_road created
```

I also checked with ffprobe:
```

ffprobe -print_format json -show_format -show_streams /home/pncanas/Desktop/annotator/dmd/gA/1/s1/gA_1_s1_2019-03-08T09\;31\;15+01\;00_rgb_body.mp4
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
{
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/pncanas/Desktop/annotator/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_rgb_body.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:03:47.22, start: 0.000000, bitrate: 15419 kb/s
    Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1280x720, 15417 kb/s, 29.76 fps, 29.76 tbr, 11904 tbn, 59.52 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High 4:4:4 Predictive",
            "codec_type": "video",
            "codec_time_base": "25/1488",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "has_b_frames": 0,
            "pix_fmt": "yuv444p",
            "level": 31,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "744/25",
            "avg_frame_rate": "744/25",
            "time_base": "1/11904",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 2704800,
            "duration": "227.217742",
            "bit_rate": "15417703",
            "bits_per_raw_sample": "8",
            "nb_frames": "6762",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "VideoHandler"
            }
        }
    ],
    "format": {
        "filename": "/home/pncanas/Desktop/annotator/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_rgb_body.mp4",
        "nb_streams": 1,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "227.218000",
        "size": "437938393",
        "bit_rate": "15419144",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "encoder": "Lavf57.83.100"
        }
    }
}
```
Maybe there is a problem when downloading the files. As I mentioned, I downloaded just one folder (/dmd/gA/1/s1/*), not everything at once. 

Can you try downloading any video (individually) that gives you an error and try again?

I leave you my system information:

- OS: Ubuntu 20.04.2 64-bit
- GCC9
- python 3.8.4
- ffmpeg 4.2.4
- ffmpeg-python 0.2.0
- OpenCV-python 4.5.2.52
- VCD 4.3.1

**Comment by psk9211** [comment]
@pncanas333

**Comment by psk9211** [comment]
@pncanas333 Hello.

I downloaded the dataset again, and it works. Seems like it was the zip download in the box causing the problems. Now all export methods are work just fine.

I never thought about the download method... Thank you for your advice!
